# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - clone
  - build
  - test
  - upload
  - deploy
  - smoke

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  buildweb:
    title: "Building web"
    type: "build"
    image_name: "lrochette/k8s-wordsmith-web"
    working_directory: "${{clone}}/web"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: true

  builddb:
    title: "Building DB"
    type: "build"
    image_name: "lrochette/k8s-wordsmith-db"
    working_directory: "${{clone}}/db"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: true

  buildapi:
    title: "Building API"
    type: "build"
    image_name: "lrochette/k8s-wordsmith-api"
    working_directory: "${{clone}}/words"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: true

  test:
    title: Update gitops repo with changes to be deployed
    type: razielt77_github/golang-test
    arguments:
      WORKING_DIRECTORY: '${{clone}}'
      REPO_NAME: '${{CF_REPO_NAME}}'
      COMMAND: gofmt -d web/dispatcher.go
    stage: "test"

  Push-web:
    title: Pushing web to Docker Registry
    type: push
    stage: upload
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
      - latest
    candidate: '${{buildweb}}'
    image_name: lrochette/k8s-wordsmith-web
    registry: dockerhub

  Push-DB:
    title: Pushing DB to Docker Registry
    type: push
    stage: upload
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
      - latest
    candidate: '${{builddb}}'
    image_name: lrochette/k8s-wordsmith-db
    registry: dockerhub

  Push-API:
    title: Pushing API to Docker Registry
    type: push
    stage: upload
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
      - latest
    candidate: '${{buildapi}}'
    image_name: lrochette/k8s-wordsmith-api
    registry: dockerhub

  DeployWeb:
    title: deploying web to GCE
    type: deploy
    stage: deploy
    kind: kubernetes
    cluster: 'cfcluster@cfproj'
    namespace: default
    service: web
    candidate:
       image: ${{buildweb}}
       registry: dockerhub

  DeployAPI:
    title: deploying API to GCE
    type: deploy
    stage: deploy
    kind: kubernetes
    cluster: 'cfcluster@cfproj'
    namespace: default
    service: web
    candidate:
       image: ${{buildapi}}
       registry: dockerhub

  DeployDB:
    title: deploying DB to GCE
    type: deploy
    stage: deploy
    kind: kubernetes
    cluster: 'cfcluster@cfproj'
    namespace: default
    service: web
    candidate:
       image: ${{builddb}}
       registry: dockerhub

  smokingTests:
    stage: smoke
    title: test web app
    image: 'byrnedo/alpine-curl'
    commands:
      - "curl web:8080"
    services:
      composition:
        web:
          image: '${{buildweb}}'
          ports:
            - 8080
