# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - clone
  - build
  - test
  - upload
  - deploy

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "lrochette/k8s-wordsmith-demo"
    working_directory: "${{clone}}/web"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: true

  test:
    title: Update gitops repo with changes to be deployed
    type: razielt77_github/golang-test
    arguments:
      WORKING_DIRECTORY: '${{clone}}'
      REPO_NAME: '${{CF_REPO_NAME}}'
      COMMAND: gofmt -d web/dispatcher.go
    stage: "test"

  MyPushStep:
    title: Pushing to Docker Registry
    type: push
    stage: upload
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    candidate: '${{build}}'
    image_name: lrochette/k8s-wordsmith-demo
    registry: dockerhub # Name of your integration as was defined in the Registry screen

  Deploy:
    title: deploying to GCE
    type: helm
    stage: deploy
    chart_name: cfchart
    release_name: first
    helm_version: 3.0.1
    kube_context: my-first-cluster-1
