# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - clone
  - build
  - test
  - upload
  - deploy

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  buildweb:
    title: "Building web"
    type: "build"
    image_name: "lrochette/k8s-wordsmith-web"
    working_directory: "${{clone}}/web"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: true

  builddb:
    title: "Building DB"
    type: "build"
    image_name: "lrochette/k8s-wordsmith-db"
    working_directory: "${{clone}}/db"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: true

  buildapi:
    title: "Building API"
    type: "build"
    image_name: "lrochette/k8s-wordsmith-api"
    working_directory: "${{clone}}/words"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: true

  test:
    title: Update gitops repo with changes to be deployed
    type: razielt77_github/golang-test
    arguments:
      WORKING_DIRECTORY: '${{clone}}'
      REPO_NAME: '${{CF_REPO_NAME}}'
      COMMAND: gofmt -d web/dispatcher.go
    stage: "test"

  MyPushStep:
    title: Pushing to Docker Registry
    type: push
    stage: upload
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    candidate: '${{buildweb}}'
    image_name: lrochette/k8s-wordsmith-web
    registry: dockerhub

  MyPushStep:
    title: Pushing to Docker Registry
    type: push
    stage: upload
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    candidate: '${{builddb}}'
    image_name: lrochette/k8s-wordsmith-db
    registry: dockerhub

  MyPushStep:
    title: Pushing to Docker Registry
    type: push
    stage: upload
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    candidate: '${{buildapi}}'
    image_name: lrochette/k8s-wordsmith-api
    registry: dockerhub

  Deploy:
    title: deploying to GCE
    type: deploy
    stage: deploy
    kind: kubernetes
    cluster: my-first-cluster-1
    #kube_context: my-first-cluster-1
    namespace: default
    service: web
    #file_path: ./kube-deployment.yml
    candidate:
       image: lrochette/k8s-wordsmith-web:${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
       registry: dockerhub
